/**
 * App configuration
 * @author Martin Vach
 */

var lang_module = angular.module('appLang', []);
var lang_data = {
    'languages': {
        'en': {
            "Attention": "Attention",
            "Table": "Table of Content",
            "Product": "Product Data",
            "Vendor": "Manufacturer",
            "Dimensions": "Dimensions (WxHxL)",
            "Weight": "Weight",
            "NWI": "Network Wide Inclusion",
            "MSRP": "MSRP",
            "Manual": "Users Manual",
            "No": "No",
            "Yes": "Yes",
            "Groups": "Association Groups",
            "Configuration": "Configuration Parameter",
            "Cert": "Z-Wave Certification Number",
            "EAN": "EAN Code",
            "Battery": "Battery",
            "Basic": "Basic Device Type",
            "Generic": "Basic Device Function",
            "Remote": "Portable Controller",
            "Controller": "Static Controller",
            "Sensor": "Sensor ",
            "Inclusion": "Inclusion Options",
            "Actor": "Actuator",
            "Router": "Routing active",
            "NWI2": "Network-Wide",
            "FLIRS": "Battery/Listening",
            "Wakeup": "Battery/Wakeup",
            "BinarySwitch": "Binary Switch",
            "MultilevelSwitch": "Multilevel Switch",
            "RemoteSwitch": "Remote Switch",
            "Thermostat": "Thermostat",
            "MultilevelSensor": "MultilevelSensor",
            "BinarySensor": "BinarySensor",
            "Meter": "Meter",
            "Gateway": "Gateway",
            "Lock": "Lock",
            "SKU": "Order Number",
            "ZEanCode": "EAN Number",
            "ZManufacturersName": "Manufacturer",
            "ZProductsSku": "Order Number",
            "ZPrice": "Price (EU)",
            "ZNetWeight": "Weight Net (gr)",
            "ZTotWeight": "Weight Total (kg)",
            "ZDimensions": "Dimensions WxHxL (cm)",
            "Categories": "Categories",
            "Description": "Description",
            "Complete manual": "Complete Manual",
            "Short version": "Short Manual",
             "Products": "Products",
              "Z-Wave Plus": "Z-Wave Plus"

        },
        'de': {
            "Attention": "Achtung",
            "Table": "Inhaltsverzeichnis",
            "Product": "Produktdaten",
            "Vendor": "Hersteller",
            "Dimensions": "Abmessungen (HxBxL)",
            "Weight": "Gewicht",
            "NWI": "Netzweite Inklusion",
            "MSRP": "Empf. Preis (netto)",
            "Manual": "Handbuch",
            "No": "Nein",
            "Yes": "Ja",
            "Groups": "Steuerungdgruppem",
            "Configuration": "Konfigurationsparameter",
            "Cert": "Zertifizierungsnummer",
            "EAN": "EAN Code",
            "Battery": "Batterie",
            "Basic": "Netzverhalten",
            "Generic": "Geräte-Grundfunktion",
            "Remote": "Portable Steuerung",
            "Controller": "Steuerzentrale ",
            "Sensor": "Sensor ",
            "Inclusion": "Inklusion-Optionen",
            "Actor": "Aktor",
            "Router": "aktives Routing",
            "NWI2": "Netzweit",
            "FLIRS": "Batterie - aktiv",
            "Wakeup": "Batterie - Aufweckinterval",
            "BinarySwitch": "Ein/Aus Schalter",
            "MultilevelSwitch": "Analoger Schalter",
            "RemoteSwitch": "Fernsteuerung",
            "Thermostat": "Heizungsthermostat",
            "MultilevelSensor": "Analoger Sensor",
            "BinarySensor": "Digitaler Sensor",
            "Meter": "Verbrauchszähler",
            "Gateway": "Steuerzentrale des Netzes",
            "Lock": "Tür-Schloss",
            "ZEanCode": "EAN-Nummer",
            "SKU": "Bestellnummer",
            "ZManufacturersName": "Hersteller",
            "ZProductsSku": "Bestellnummer",
            "ZPrice": "Preis (EU)",
            "ZNetWeight": "Gewicht Netto (kg)",
            "ZTotWeight": "Gewicht Brutto (gr)",
            "ZDimensions": "Abmessungen HxBxL (cm)",
            "Categories": "Kategorien",
            "Description": "Beschreibung",
            "Complete manual": "Komplett-Handbuch",
            "Short version": "Kurz-Handbuch",
            "Products": "Produkte",
              "Z-Wave Plus": "Z-Wave Plus"

        }
    }
};
angular.forEach(lang_data, function(key, value) {
    lang_module.constant(value, key);
});